/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umessick.PAM;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.InputStreamReader;
import java.io.Reader;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;


/**
 *
 * @author uam65345
 */
public class ActivityLog extends javax.swing.JFrame {

    /**
     * Creates new form ActivityLog
     */
    public ActivityLog() {
        initComponents();
        
        String[] columnTitles = { "Date", "Activity", "Value", "description", "Comment" };
        
        try(Reader reader = new InputStreamReader(PAMVIEW.class.getResourceAsStream("/json/ursula/data.json"), "UTF-8")) {
            Gson gson = new GsonBuilder().create();
            PAMRecord p = gson.fromJson(reader, PAMRecord.class);
            System.out.println(p);
        } catch (Exception e) {
            System.out.print("ERROR :: " + e.getMessage());
        }
        
        PAMRecord rec = new PAMRecord();
        rec.date = Helpers.getDate(1982, 11, 16);
        rec.activity = "Running";
        rec.value = "2";
        rec.description = "This is something";
        rec.comment = "Comment";      
       
        EditableTableModel model = new EditableTableModel(columnTitles);  
        
        for(int i = 0;i<10;i++) {            
            Object[] record = new Object[]{
                rec.date,
                rec.activity,
                rec.value, 
               rec.description,
                rec.comment
            };            
            model.insertRow(record);
        }
                
        jTable_log.setModel(model);
        jTable_log.createDefaultColumnsFromModel();
        
        /* Format Date */
//        try {
//            JFormattedTextField tf = new JFormattedTextField(new SimpleDateFormat("dd/MM/yyyy"));
//            MaskFormatter dateMask = new MaskFormatter("##/##/####");
//            dateMask.install(tf);
//            jTable_log.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(tf));
//        } catch (ParseException ex) {
//            System.out.print("error");
//        }
        
        jTable_log.getColumnModel().getColumn(0).setCellEditor(new DateTableCellEditor());
                    
        /* Format Drop Down */
        String[] bloodGroups = { "Sleep", "Work", "School"};
        JComboBox comboBox = new JComboBox(bloodGroups);
        jTable_log.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(comboBox));
        
        jTable_log.setRowHeight(25);
        jTable_log.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_Activity = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_log = new javax.swing.JTable();
        btn_addActivity = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_nav_home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_Activity.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Activity Log"));

        jTable_log.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_log);

        btn_addActivity.setText("Add New Activity");
        btn_addActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActivityActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btn_nav_home.setText("Home");
        btn_nav_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nav_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_nav_home)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(btn_nav_home)
                .addContainerGap())
        );

        javax.swing.GroupLayout jp_ActivityLayout = new javax.swing.GroupLayout(jp_Activity);
        jp_Activity.setLayout(jp_ActivityLayout);
        jp_ActivityLayout.setHorizontalGroup(
            jp_ActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ActivityLayout.createSequentialGroup()
                .addGroup(jp_ActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_ActivityLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE))
                    .addComponent(btn_addActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp_ActivityLayout.setVerticalGroup(
            jp_ActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ActivityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_Activity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_Activity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActivityActionPerformed
        EditableTableModel model = (EditableTableModel) jTable_log.getModel();
        
        /* Add Blank Object */
        Object[] record = new Object[]{
            new Date(),
            "",
            "",
            "",
            ""
        };            
        model.insertRow(record);
        jTable_log.setModel(model);       
    }//GEN-LAST:event_btn_addActivityActionPerformed

    private void btn_nav_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nav_homeActionPerformed
        PAMHome frame = new PAMHome();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_nav_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActivityLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActivityLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActivityLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActivityLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActivityLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addActivity;
    private javax.swing.JButton btn_nav_home;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_log;
    private javax.swing.JPanel jp_Activity;
    private javax.swing.JPanel jp_navigation;
    // End of variables declaration//GEN-END:variables
 }
