/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umessick.PAM;

import com.google.gson.Gson;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author uam65345
 */


public class PAMVIEW extends javax.swing.JFrame {

    /**
     * Creates new form PAMVIEW
     */
    public PAMVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Record_jPanel = new javax.swing.JPanel();
        lb_JSON = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_JSON = new javax.swing.JTextArea();
        btn_JSON = new javax.swing.JButton();
        btn_LoadData = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Records = new javax.swing.JTable();
        tbl_Activity_Three = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Activity_One = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_Activity_Two = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Record_jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Record"));

        lb_JSON.setLabelFor(tb_JSON);
        lb_JSON.setText("JSON");
        lb_JSON.setToolTipText("??");

        tb_JSON.setColumns(20);
        tb_JSON.setRows(5);
        jScrollPane1.setViewportView(tb_JSON);

        btn_JSON.setText("Read JSON");
        btn_JSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_JSONActionPerformed(evt);
            }
        });

        btn_LoadData.setText("Load Data");
        btn_LoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoadDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Record_jPanelLayout = new javax.swing.GroupLayout(Record_jPanel);
        Record_jPanel.setLayout(Record_jPanelLayout);
        Record_jPanelLayout.setHorizontalGroup(
            Record_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Record_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Record_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Record_jPanelLayout.createSequentialGroup()
                        .addComponent(lb_JSON)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Record_jPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_LoadData)
                        .addGap(35, 35, 35)
                        .addComponent(btn_JSON)))
                .addContainerGap())
        );
        Record_jPanelLayout.setVerticalGroup(
            Record_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Record_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_JSON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Record_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_JSON)
                    .addComponent(btn_LoadData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_Records.setAutoCreateRowSorter(true);
        jTable_Records.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_Records);

        tbl_Activity_One.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_Activity_One);

        tbl_Activity_Three.addTab("Activity One", jScrollPane3);

        tbl_Activity_Two.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_Activity_Two);

        tbl_Activity_Three.addTab("Activity Two", jScrollPane4);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        tbl_Activity_Three.addTab("Activity Three", jScrollPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Record_jPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tbl_Activity_Three, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Record_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbl_Activity_Three, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_JSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_JSONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_JSONActionPerformed

    private void btn_LoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoadDataActionPerformed
        PAMRecord rec = new PAMRecord();
        rec.date = Helpers.getDate(1977, 7, 17);
        rec.activity = "Running";
        rec.value = "2";
        rec.description = "This is something";
        rec.comment = "Comment";
       
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("date");
        model.addColumn("activity");
        model.addColumn("value");
        model.addColumn("description");
        model.addColumn("comment");
        
        
        for(int i = 0;i<20;i++) {
            model.insertRow(0, new Object[]{
                rec.date,
                rec.activity,
                rec.value,
                rec.description,
                rec.comment
            });   
        }
        
        
      
        
        jTable_Records.setModel(model);
        tbl_Activity_One.setModel(model);
    }//GEN-LAST:event_btn_LoadDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAMVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAMVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAMVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAMVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAMVIEW().setVisible(true);
            }
        });
        
//        try(Reader reader = new InputStreamReader(PAMVIEW.class.getResourceAsStream("/json/data.json"), "UTF-8")) {
//            Gson gson = new GsonBuilder().create();
//            PAMRecord p = gson.fromJson(reader, PAMRecord.class);
//            System.out.println(p);
//        } catch (Exception e) {
//            System.out.print("ERROR :: " + e.getMessage());
//        }
       
        PAMRecord rec = new PAMRecord();
        rec.date = Helpers.getDate(1977, 7, 17);
        rec.activity = "Running";
        rec.value = "2";
        rec.description = "This is something";
        rec.comment = "Comment";
        Gson gson = new Gson();
        String json = gson.toJson(rec); 
        System.out.println(json);
        
        PAMRecord[] recs = {rec,rec,rec,rec};
        String json2 = gson.toJson(recs);
        System.out.println(json2);
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("date");
        model.addColumn("activity");
        model.addColumn("value");
        model.addColumn("description");
        model.addColumn("comment");
        
        
        model.insertRow(0, new Object[]{
            rec.date,
            rec.activity,
            rec.value,
            rec.description,
            rec.comment
        });
        
        
        
//         DefaultTableModel model = new DefaultTableModel();
//            JTable table = new JTable(model);
//            model.addColumn("ID");
//            model.addColumn("First Name");
//            model.addColumn("Last Name");
//
//
//            while (res.next()) {
//                if (res.wasNull()) {
//                    //-- ADD RECORDSET DATA TO JTABLE MODEL
//                    model.insertRow(0, new Object[]{
//                                res.getString("Id"),
//                                res.getString("firstName"),
//                                res.getString("lastName")
//                            });
//
//                }
//
//            }
//            //-- ADD THIS MODEL TO THE JTABLE
//            tbl_Results.setModel(model);
        
       
        
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Record_jPanel;
    private javax.swing.JButton btn_JSON;
    private javax.swing.JButton btn_LoadData;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable_Records;
    private javax.swing.JLabel lb_JSON;
    private javax.swing.JTextArea tb_JSON;
    private javax.swing.JTable tbl_Activity_One;
    private javax.swing.JTabbedPane tbl_Activity_Three;
    private javax.swing.JTable tbl_Activity_Two;
    // End of variables declaration//GEN-END:variables
}

